### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#1]
**User Story**
As a customer, I would like the website to have a clear navigation area so that I can use get from page to page with easy.

**Acceptance Criteria**

- [x] The navbar be easy to see at the top of the screen.
- [x] It will be responsive on all devices, changing to a dropdown/collapsable list on smaller screens and will be side by side on larger screens.
- [x] The color on the nav bar will be well contrasted.

**Tasks**

- [x] Create a navbar within the head of the HTML section.
- [x] Apply the dropdown/collapsable bootstrap css to the nav bar.
- [x] Apply color to the navbar ensuring contrast between each one.
- [x] Ensure responsiveness of the navbar from small devices to large.
