### ISSUE TITLE
Clear information on front page

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#2]
**User Story**
As a customer, I would like there to be clear information on the first page I see so that I know immediately I'm visiting the correct site.

**Acceptance Criteria**

- [x] Information will be displayed clearly as soon as the page is opened, with a brief but information decription of the business.
- [x] Colors on the page will be simple and not distracting to users.
- [x] Include the logo of the business above company's information.
- [x] Faced image of a past job the business has completed in the background of the page.

**Tasks**

- [x] Place a logo of the business, large and centered, at the top of the home page.
- [x] Bold clear text for the description underneath the business logo.
- [x] Upload roof image from company to apply to the background, opaque, just enough so that the description is still clear on top.
- [x] Use [Color Contrast Grid](https://contrast-grid.eightshapes.com/) to help determine the color palette of the site.
