### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#3]
**User Story**
As a customer, I want the contact details to be accessible on all pages so that I can find them with just one click.

**Acceptance Criteria**

- [x] Clear contact details containing, company name, location and phone number (with the name of the owner alongside).
- [x] Ensure that the contact details are in one area of the page throughhout the site.

**Tasks**

- [x] Create a contact section at the footer of the page within the body element of the HTML.
- [x] Ensure that the section is fully repsonsive on all devices.
- [x] Create a link in the navbar that will take user to the section on all pages.
