### ISSUE TITLE
Services page

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#4]
**User Story**
As a customer, I want to be able to see what the company has to offer so that I can make an informative decision to call them.

**Acceptance Criteria**

- [x] List all the jobs undertaken by the company in a section on the page.
- [x] Include images of the jobs completed in a carousel underneath the list.
- [ ] The option to click on an image in the carousel/gallery with description underneath.

**Tasks**

- [ ] Create a 'pop-out' of the image clicked with a description of what work was done on the job.
- [x] Create a carousel of images provided by the company and place at the center of the page below list.
- [x] List the jobs in a seperate section at the top of the page in clear, easy to read text.

**Comment by chloejones9464** [comment]
Creating the popout images and decription for the gallery page instead of services page
