### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#5]
**User Story**
As the owner of the company, I would like to include various jobs we've completed on the website so that customers can view what we can do and to the standard we're proud of.

**Acceptance Criteria**

- [x] Include a page with interactive images to click on and see description.
- [x] Page will be full of images of the jobs undertaken.
- [x] It will need to be responsive on all devices.
- [ ] 

**Tasks**

- [x] Create new page for Gallery and add all images into a grid.
- [x] Receive images from company to upload.
- [x] Alter the responsiveness so that the page looks user friendly on all devices.
