### ISSUE TITLE
Call Now button for mobiles

### ISSUE THREAD

**Issue by chloejones9464** [chloejones9464/a-and-b-roofing-services#6]
**User Story**
As the owner/customer, I want to have a Call Now button for an emergency or ease of contact so that the company can be contacted right-away.

**Acceptance Criteria**
- [x] To include a Call Now button in the navbar for mobile devices only.
- [x] The button to be visable outside of the navbar, clear to see.
- [ ] 

**Tasks**
- [x] Create a button for the Call Now bar, using the help of an external site for guidence (include link in README.md)
- [x] Position the button so that it is outside of the collapsable navbar and clear to click on any page at any time.
